theme = "nord"

[editor]
line-number = "relative"
mouse = true
cursorline = true
cursorcolumn = false
true-color = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "version-control", "spinner"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "file-type", "file-encoding", "file-line-ending", "position-percentage", "position"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
