window:
  dimensions:
    columns: 160
    lines: 42
  padding:
    x: 7
    y: 7
  dynamic_padding: true
  decorations: Full
  startup_mode: Windowed
  title: Alacritty
  6ynamic_title: false
  opacity: 1
  option_as_alt: None

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
  size: 14
  offset:
    x: 0
    y: 1
  glyph_offset:
    x: 0
    y: 0

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'
  command: None

cursor:
  style: Beam
  vi_mode_style: Block
  unfocused_hollow: true
  thickness: 0.15

key_bindings:
  - { key: N,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: F,   mods: Control|Shift, action: ToggleFullscreen }
  - { key: M,   mods: Control|Shift, action: Minimize }

env:
  TERM: xterm-256color
  ZDOTDIR: /Users/markus/.config/zsh

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux new -A -s base -n main"

# Color-Theme
import:
 - ~/.config/alacritty/color_nord.yml

