import = ["/home/markus/.config/alacritty/theme.toml"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[cursor]
style = "Beam"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Block"

[env]
TERM = "alacritty"
ZDOTDIR = "/home/markus/.config/zsh"

[font]
size = 11
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }
builtin_box_drawing = false
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono",  style = "Bold Italic" }

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
{ key = "M", mods = "Control|Shift", action = "Minimize" }
]

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/tmux"
args = ["new", "-A", "-sbase"]

[window]
startup_mode = "Windowed"
dimensions = { columns = 140, lines = 38 }
padding = { x = 7, y=7 }
dynamic_padding = true
title = "Alacritty"
dynamic_title = true
opacity = 1
blur = false
decorations = "Full"
decorations_theme_variant = "None"

