#!/usr/bin/env sh

# Muss noch etwas installiert werden?
inst_err=''

if [ ! $(which tic) ]; then
    echo "tic muss noch installiert werden."
    inst_err='ja'
fi

if [ ! $(which curl) ]; then
    echo "curl muss noch installiert werden."
    inst_err='ja'
fi

if [ ! $(which zsh) ]; then
    echo "zsh muss noch installiert werden."
    inst_err='ja'
fi

if [ $inst_err ]; then
    exit
fi


# Warnungen wenn eine Anwendung fehlt.
if [ ! $(which nvim) ]; then
    echo "nvim fehlt!."
fi

if [ ! $(which nano) ]; then
    echo "nano fehlt."
fi

if [ ! $(which tmux) ]; then
    echo "tmux fehlt."
fi


# Installationsverzeichnis
CONF="$HOME/.config"

# Terminfo-Dateien übersetzen
tic -x "$CONF/dotfiles/terminfo/tmux-256color.terminfo"
tic -x "$CONF/dotfiles/terminfo/xterm-256color-italic.terminfo"
echo "terminfo-Dateien neu erstellen."


# Konfigurationsverzeichnise vorhanden

if [ ! -d "$CONF" ]; then
    echo "~/.config wird erstellt."
    mkdir "$CONF"
fi

if [ ! -d "$CONF/zsh" ]; then
    echo "~/.config/zsh wird erstellt."
    mkdir "$CONF/zsh"
fi

if [ ! -d "$CONF/nvim" ]; then
    echo "~/.config/nvim wird erstellt."
    mkdir "$CONF/nvim"
fi

if [ ! -d "$CONF/nano" ]; then
    echo "~/.config/nano wird erstellt."
    mkdir "$CONF/nano"
fi

if [ ! -d "$CONF/tmux" ]; then
    echo "~/.config/tmux wird erstellt."
    mkdir "$CONF/tmux"
fi

if [ ! -d "$CONF/alacritty" ]; then
    echo "~/.config/alacritty wird erstellt."
    mkdir "$CONF/alacritty"
fi


# Symbolische Links erstellen

if [ ! -e "$CONF/.zshrc" ]; then
    echo "link für zshrc wird erstellt."
    ln -s "$CONF/dotfiles/zshrc" "$CONF/zsh/.zshrc"
fi

if [ ! -e "$CONF/nvim/init.vim" ]; then
    echo "link für init.vim wird erstellt."
    ln -s "$CONF/dotfiles/vimrc" "$CONF/nvim/init.vim"
fi

if [ ! -e "$CONF/nano/nanorc" ]; then
    echo "link für nanorc wird erstellt."
    ln -s "$CONF/dotfiles/nanorc" "$CONF/nano/nanorc"
fi

if [ ! -e "$CONF/tmux.conf" ]; then
    echo "link für tmux.conf wird erstellt."
    ln -s "$CONF/dotfiles/tmux.conf" "$CONF/tmux/tmux.conf"
fi

if [ ! -e "$CONF/alacritty/alacritty.yml" ]; then
    echo "link für alacritty.yml wird erstellt."
    cp alacritty.yml.bp alacritty.yml
    echo "  ZDOTDIR: $CONF/zsh" >> alacritty.yml
    ln -s "$CONF/dotfiles/alacritty.yml" "$CONF/alacritty/alacritty.yml"
fi

# nvim Plugins
if [ ! -e "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
    echo "plug.vim herunterladen:"
    curl -flo "$HOME/.local/share/nvim/site/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
fi
