#!/usr/bin/env sh

# muss noch etwas installiert werden?
# Wenn ja, dann wird das scripüt beendet.
inst_err=''

if [ ! $(which nvim) ]; then
    echo "nvim muss noch installiert werden."
    inst_err='ja'
fi

if [ ! $(which tmux) ]; then
    echo "tmux muss noch installiert werden."
    inst_err='ja'
fi

if [ ! $(which zsh) ]; then
    echo "zsh muss noch installiert werden."
    inst_err='ja'
fi

if [ ! $(which tic) ]; then
    echo "tic muss noch installiert werden."
    inst_err='ja'
fi

if [ ! $(which git) ]; then
    echo "git muss noch installiert werden."
    inst_err='ja'
fi

if [ ! $(which curl) ]; then
    echo "curl muss noch installiert werden."
    inst_err='ja'
fi

if [ $inst_err ]; then
    exit
fi

# Terminfo-Dateien übersetzen
tic -x "$HOME/.dotfiles/terminfo/tmux-256color.terminfo"
tic -x "$HOME/.dotfiles/terminfo/xterm-256color-italic.terminfo"

# airprompt von git herunterladen
if [ ! -d "$HOME/.dotfiles/airprompt" ]; then
    echo "lade airprompt runter:"
    git clone "https://github.com/sonnmar/airprompt" "$HOME/.dotfiles/airprompt"
fi

# Konfigurationsverzeichnise vorhanden
if [ ! -d "$HOME/.config" ]; then
    echo ".config wird erstellt."
    mkdir "$HOME/.config"
fi

if [ ! -d "$HOME/.config/nvim" ]; then
    echo ".config/nvim wird erstellt."
    mkdir "$HOME/.config/nvim"
fi

if [ ! -d "$HOME/.tmux" ]; then
    echo ".tmux wird erstellt."
    mkdir "$HOME/.tmux"
fi

# Symbolische Links erstellen
if [ ! -e "$HOME/.config/nvim/init.vim" ]; then
    echo "link für init.vim wird erstellt."
    ln -s "$HOME/.dotfiles/vimrc" "$HOME/.config/nvim/init.vim"
fi

if [ ! -e "$HOME/.tmux.conf" ]; then
    echo "link für tmux.conf wird erstellt."
    ln -s "$HOME/.dotfiles/tmux.conf" "$HOME/.tmux.conf"
fi

if [ ! -e "$HOME/.zshrc" ]; then
    echo "link für zshrc wird erstellt."
    ln -s "$HOME/.dotfiles/zshrc" "$HOME/.zshrc"
fi

# nvim Plugins
if [ ! -e "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
    echo "plug.vim herunterladen:"
    curl -flo "$HOME/.local/share/nvim/site/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
fi

# tmux Plugins
if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
    echo "tpm herunterladen:"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

