# BASE SETTINGS

# Prefix Control-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Tastenkürzel zum Laden der Konfigurationsdatei:
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# split panes using | and -
bind + split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Nummerierung der Fenster und Teilfenster jeweils mit 1 beginnen:
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# and use C-h and C-l to cycle thru panes
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# resize panes using PREFIX H, J, K, L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Truecolor
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'


# DESIGN CHANGES

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-style 24
setw -g clock-mode-colour colour253

#  modes
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# panes
set -g pane-border-style 'fg=colour237 bg=colour0'
set -g pane-active-border-style 'fg=colour253 bg=colour0'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=colour253 bg=colour235'
set -g status-left '#[fg=colour253,bg=colour237] #h  #S #[fg=colour237,bg=colour235]#[fg=colour253,bg=colour235] '
set -g status-right '#[fg=colour241,bg=colour235]#[fg=colour253,bg=colour241] #{online_status} #[fg=colour239,bg=colour241]#[fg=colour253,bg=colour239] R:#{ram_percentage}  C:#{cpu_percentage}  B:#{battery_percentage} #[fg=colour237,bg=colour239]#[fg=colour253,bg=colour237] %d.%m.%Y  %H:%M #[fg=colour215,bg=colour237]'
set -g status-right-length 60
set -g status-left-length 50

setw -g window-status-current-style 'fg=colour253 bg=colour241'
setw -g window-status-current-format '#[fg=colour235,bg=colour241]#[fg=colour253 bg=colour241] #I:#W#F #[fg=colour241,bg=colour235]'

setw -g window-status-separator ''

setw -g window-status-style 'fg=colour253 bg=colour239'
setw -g window-status-format '#[fg=colour235,bg=colour237]#[fg=colour253, bg=colour237] #I:#W#F #[fg=colour237,bg=colour235]'

# bell
setw -g window-status-bell-style 'fg=colour253 bg=colour239 bold'

# messages
set -g message-style 'fg=colour253 bg=colour239 bold'


# Plugins

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'sonnmar/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-online-status'

set -g @online_icon "online"
set -g @offline_icon "offline"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
