#
# Environment
#

# path
export PATH="$PATH:$HOME/.local/bin"

# xdg
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# programs
export PAGER="less"
export EDITOR="nvim"

# locale-settings
export LANG="de_DE.UTF-8"

