#
# zsh Konfigurationsdatei
#

# create ".local/share/zsh" if not exists
[ ! -d "${XDG_DATA_HOME:-$HOME/.local/share}/zsh" ] && mkdir "${XDG_DATA_HOME:-$HOME/.local/share}/zsh"

# Basics
setopt correct                  # autocorrection
setopt autocd                   # test ls for unknown commands to easy cd
setopt no_beep                  # no noise


# Jobcontrol
setopt longlistjobs             # show PID for suspended processes
setopt notify                   # show state of background processes
# setopt nohup                    # disown jobs if shell stops


# Globbing and findig
# setopt no_nomatch               # don't show "zsh: no match found..."
# setopt null_glob                # show empty line in case of "no match found"
setopt extendedglob             # extended globbing
setopt nocaseglob               # case indenditiv globbing
setopt noglobdots               # don't match dotfiles
setopt rcexpandparam            # expand arrays with parameters
setopt numericglobsort          # numeric sort of filenames


# ZLE
bindkey -A viins main           # viins as default keymap
# bindkey -A emacs main           # emacs as default keymap

# source keybindings
source "$ZDOTDIR/bindings.zsh"

# vimkeys for menuselection
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char


# Complition
autoload -Uz compinit
compinit -u -d "$HOME/.local/share/zsh/zcompdump-$ZSH_VERSION"
setopt hash_list_all
setopt completeinword

zstyle ':completion:*' menu yes select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' rehash true                              # automatically find new executables in path
zstyle ':completion:*' accept-exact '*(N)'                      # Speed up completion
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.cache/zsh


# Push / Pop
setopt auto_pushd               # alte Directoryeinträge stacken
setopt pushd_ignore_dups        # doppelte Einträge vermeiden


# History
HISTFILE="$HOME/.local/share/zsh/history"
SAVEHIST=500
HISTSIZE=1000
setopt sharehistory             # History zwischen den zsh-Instanzen tauschen
setopt appendhistory            # Historyeinträge anhängen
setopt extendedhistory          # chronologische Ablage der History be mehrere Instanzen
setopt histignorealldups        # Dupletten in der History vermeiden
setopt histreduceblanks         # blanks in Einträge komprimieren
setopt histnostore              # Befehle zur History nicht ablegen
setopt histignorespace          # Befehle mit Blank am Anfang nicht speichern


# Aliase-File
source "$ZDOTDIR/aliases.zsh"


# fzf-Integration
eval "$(fzf --zsh)"


# Plugin-Manager: https://github.com/zap-zsh/zap
# Install: git clone -b "master" https://github.com/zap-zsh/zap.git "$HOME/.local/share/zap"
# Activate:
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
# Plugins:
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "sonnmar/visiprompt"

