#
# zsh Konfigurationsdatei
#

# Allgemein
setopt correct                  # Autocorrectur
setopt autocd                   # nicht gefundene Commands als Directory auffassen und ls testen
setopt no_beep                  # kein Krach


# Jobcontrol
setopt longlistjobs             # PID auch von suspendierten Prozessen anzeigen
setopt notify                   # Status von Backroundprozessen anzeigem
#setopt nohup                   # Jobs beim stoppen der Shell von dieser disownen


# Globbing and findig
#setopt no_nomatch              # "zsh: no match found..." verhindern, gibt nur den Begriff aus
#setopt null_glob               # gibt bei "no match found" eine leere Zeile aus
setopt extendedglob             # erweitertes Globbing
setopt nocaseglob               # Case indenditiv globbing
setopt noglobdots               # keine Dotfiles matchen
setopt rcexpandparam            # Arrayerweiterung mit Parametern
setopt numericglobsort          # Dateinamen nummerisch sortieren


# ZLE-mode and keysettings
bindkey -A viins main           # viins as default keymap

# vimkeys for menuselection
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char

# vimkeys in vi normal mode
bindkey -M vicmd "j" down-line-or-search
bindkey -M vicmd "k" up-line-or-search
bindkey -M vicmd "\e[3~" delete-char              # delete

# keys in vi insert mode
bindkey -M viins "\e[A" up-line-or-search         # arrow up
bindkey -M viins "\e[B" down-line-or-search       # arrow down
bindkey -M viins "\e[3~" delete-char              # delete
bindkey -M viins "\e[1~" beginning-of-line        # pos 1 in tmux
bindkey -M viins "\e[4~" end-of-line              # end in tmux

# keys in emacs mode
bindkey -M emacs "\e[A" up-line-or-search         # arrow up
bindkey -M emacs "\e[B" down-line-or-search       # arrow down
bindkey -M emacs "\e[3~" delete-char              # delete
bindkey -M emacs "\e[1~" beginning-of-line        # pos 1 in tmux
bindkey -M emacs "\e[4~" end-of-line              # end in tmux


# Vervollständigung
autoload -Uz compinit
compinit -u -d "$HOME/.local/share/zsh/zcompdump-$ZSH_VERSION"
setopt hash_list_all
setopt completeinword

zstyle ':completion:*' menu yes select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' rehash true                              # automatically find new executables in path
zstyle ':completion:*' accept-exact '*(N)'                      # Speed up completion
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.cache/zsh


# Push / Pop
setopt auto_pushd               # alte Directoryeinträge stacken
setopt pushd_ignore_dups        # doppelte Einträge vermeiden


# History
HISTFILE="$HOME/.local/share/zsh/history"
SAVEHIST=500
HISTSIZE=1000
setopt sharehistory             # History zwischen den zsh-Instanzen tauschen
setopt appendhistory            # Historyeinträge anhängen
setopt extendedhistory          # chronologische Ablage der History be mehrere Instanzen
setopt histignorealldups        # Dupletten in der History vermeiden
setopt histreduceblanks         # blanks in Einträge komprimieren
setopt histnostore              # Befehle zur History nicht ablegen
setopt histignorespace          # Befehle mit Blank am Anfang nicht speichern


# Pfade
export PATH=".:$HOME/Library/Python/3.9/bin:$HOME/bin:$PATH"
export PAGER=less
export EDITOR=nvim
# export XDG_CURRENT_DESKTOP=Unity
# export MOZ_ENABLE_WAYLAND=1



# einige sinnvolle aliase
alias mex='chmod 755'
alias nex='chmod 644'
alias ls='ls --color'
alias ll='ls -lh'
alias la='ls -A'
alias lla='la -la'
alias llaa='la -lh@'
alias ..='cd ..'
alias more='less'
alias vi='nvim'
alias vim='nvim'


# Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "$HOME/Projekte/visiprompt/prompt.sh"

